### ISSUE TITLE
Fixng error: ‘vsnprintf’ is not a member of ‘std’

### ISSUE THREAD

**Issue by stievie** [mgerhardy/simpleai#32]
Hi again,

there is an error in https://github.com/mgerhardy/simpleai/blob/master/src/ai/common/Log.h

The function `vsnprintf` is not part of the `std` namespace. If you just remove the `std` then it compiles, and probably makes also the Travis and AbbVeyor CI builds succeed. So GCC and MSCV have the same opinion on that.

Thanks for this great library!

**Comment by mgerhardy** [comment]
Thanks a lot for reporting it - and again thanks for using the lib ;)
